POST http://localhost:8080/api/exam//update/add/teacher
token:db970a208cc3f13c0f13cdbabff5fab5adf85a11e475b8b83350376aaf0e6d7caab1bf6c6236b257c4ee7a78ffe92558
Content-Type: application/json

{
  "tids": [
    2,
    7
  ],
  "exam": {
    "id": "2",
    "deadTime": "2019-06-18 11:00",
    "startTime": "2019-06-18 09:00",
    "status": "未分配",
    "numOfPerson":2,
    "place": "锦绣楼4楼403",
    "course": {
      "id": 4,
      "name": "高等数学"
    }
  }
}

###